grails/todo/grails-app/domain/es/ua/expertojava/todo/Category.groovy
package es.ua.expertojava.todo

class Category {

    String name
    String description
    static searchable = true

    static hasMany = [todos:Todo]

    static constraints = {
        name(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
    }

    String toString(){
        name
    }
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Person.groovy
package es.ua.expertojava.todo

class Person implements Serializable {

	private static final long serialVersionUID = 1

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	Person(String username, String password) {
		this()
		this.username = username
		this.password = password
	}

	@Override
	int hashCode() {
		username?.hashCode() ?: 0
	}

	@Override
	boolean equals(other) {
		is(other) || (other instanceof Person && other.username == username)
	}

	@Override
	String toString() {
		username
	}

	Set<Role> getAuthorities() {
		PersonRole.findAllByPerson(this)*.role
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/RequestMap.groovy
package es.ua.expertojava.todo

import groovy.transform.ToString

import org.apache.commons.lang.builder.HashCodeBuilder
import org.springframework.http.HttpMethod

@ToString(cache=true, includeNames=true, includePackage=false)
class RequestMap implements Serializable {

	private static final long serialVersionUID = 1

	String configAttribute
	HttpMethod httpMethod
	String url

	RequestMap(String url, String configAttribute, HttpMethod httpMethod = null) {
		this()
		this.configAttribute = configAttribute
		this.httpMethod = httpMethod
		this.url = url
	}

	@Override
	int hashCode() {
		new HashCodeBuilder().append(configAttribute).append(httpMethod).append(url).toHashCode()
	}

	@Override
	boolean equals(other) {
		is(other) || (
			other instanceof RequestMap &&
			other.configAttribute == configAttribute &&
			other.httpMethod == httpMethod &&
			other.url == url)
	}

	static constraints = {
		configAttribute blank: false
		httpMethod nullable: true
		url blank: false, unique: 'httpMethod'
	}

	static mapping = {
		cache true
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Role.groovy
package es.ua.expertojava.todo

class Role implements Serializable {

	private static final long serialVersionUID = 1

	String authority

	Role(String authority) {
		this()
		this.authority = authority
	}

	@Override
	int hashCode() {
		authority?.hashCode() ?: 0
	}

	@Override
	boolean equals(other) {
		is(other) || (other instanceof Role && other.authority == authority)
	}

	@Override
	String toString() {
		authority
	}

	static constraints = {
		authority blank: false, unique: true
	}

	static mapping = {
		cache true
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Todo.groovy
package es.ua.expertojava.todo

class Todo {
    User user
    String title
    String description
    Date date
    Date reminderDate
    String url
    boolean done
    Category category
    Date dateCreated
    Date lastUpdated
    Date dateDone
    ArrayList<Tag> tags = new ArrayList<Tag>();
    static searchable = [only: 'title']

    static constraints = {
        user(nullable:false)
        title(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
        date(nullable:false)
        reminderDate(nullable:true,
        validator: { val, obj ->
            Date now = new Date();
            if (val) {
                 if(obj?.date) {
                     return val.before(obj.date) && val.after(now);
                 } else {
                     return val.after(now);
                 }
            }
            return true;
        })
        url(nullable:true, url:true)
        done(nullable:false, done:false)
        category(nullable:true)
        dateDone(nullable:true)
    }

    String toString(){
        title
    }

    void addToTags(Tag tag) {
        tags.add(tag);
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/CategoryController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class CategoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryInstanceCount: Category.count()]
    }

    def show(Category categoryInstance) {
        respond categoryInstance
    }

    def create() {
        respond new Category(params)
    }

    @Transactional
    def save(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'create'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), categoryInstance.name])
                redirect categoryInstance
            }
            '*' { respond categoryInstance, [status: CREATED] }
        }
    }

    def edit(Category categoryInstance) {
        respond categoryInstance
    }

    @Transactional
    def update(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'edit'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect categoryInstance
            }
            '*'{ respond categoryInstance, [status: OK] }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TagController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class TagController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

    def show(Tag tagInstance) {
        respond tagInstance
    }

    def create() {
        respond new Tag(params)
    }

    @Transactional
    def save(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance) {
        respond tagInstance
    }

    @Transactional
    def update(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Tag tagInstance) {

        if (tagInstance == null) {
            notFound()
            return
        }

        // 'Borrado' de tareas asociadas (las pone a null)
        tagInstance.hasMany.each { it = null;}

        tagInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def confirm (Tag tagInstance) {
        respond tagInstance, view:'confirm'
        return
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TodoController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_BASIC'])
@Transactional(readOnly = true)
class TodoController {

    def searchableService

    def TodoService todoService = new TodoService();

    def TagService tagService = new TagService();

    def springSecurityService;

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        def user = springSecurityService.currentUser;
        respond Todo.findAllByUser(user, params), model:[todoInstanceCount: Todo.count()]
    }

    def show(Todo todoInstance) {
        if(todoInstance != null) todoInstance.tags.each { println it;}
        respond todoInstance;
    }

    def create() {
        params.user = springSecurityService.currentUser;
        respond new Todo(params)
    }

    def report() {
        respond Category.list()
    }

    def reportByCategory(params) {
        def selectedCategories = params.selectedCategories.collect{it.toLong()};
        respond Todo.findAllByCategoryInList(Category.getAll(selectedCategories), ["sort":"date", "order":"asc"]);
    }

    @Transactional
    def save(Todo todoInstance) {
        todoInstance.user = springSecurityService.currentUser;
        todoInstance.validate();

        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'create'
            return
        }

        todoService.saveTodo(todoInstance);

        todoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*' { respond todoInstance, [status: CREATED] }
        }
    }

    def edit(Todo todoInstance) {
        respond todoInstance
    }

    @Transactional
    def update(Todo todoInstance) {
        if (todoInstance == null) {
            notFound()
            return
        }

        if (todoInstance.hasErrors()) {
            respond todoInstance.errors, view:'edit'
            return
        }

        todoService.saveTodo(todoInstance);

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.id])
                redirect todoInstance
            }
            '*'{ respond todoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Todo todoInstance) {

        if (todoInstance == null) {
            notFound()
            return
        }

        todoService.removeTodo(todoInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Todo.label', default: 'Todo'), todoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'todo.label', default: 'Todo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def listNextTodos(Integer days) {
        respond todoService.getNextTodos(days, params),
            model:[todoInstanceCount: todoService.countNextTodos(days)],
            view:"index"
    }

    @Secured(['ROLE_ADMIN'])
    def showTodosByUser(){
        def user = User.findByUsername(params.username)
        respond Todo.findAllByUser(user);
    }

    def searchTodos = {
        def query = params.query
        if(query){
            def user = springSecurityService.currentUser;
            def userTodos = Todo.findAllByUser(user)
            def todos = searchableService.search('*' + query + '*')
            render(view: "index", model: [todoInstanceList: Todo.findAllByTitleInList(todos.results).intersect(userTodos)])
        }else{
            redirect(action: "index")
        }
    }

}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/UserController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/views/todo/_form.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>



<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="todo.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${todoInstance?.title}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="todo.description.label" default="Description" />

	</label>
	<g:textArea name="description" cols="40" rows="5" maxlength="1000" value="${todoInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'date', 'error')} required">
	<label for="date">
		<g:message code="todo.date.label" default="Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="date" precision="day"  value="${todoInstance?.date}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'reminderDate', 'error')} ">
	<label for="reminderDate">
		<g:message code="todo.reminderDate.label" default="Reminder Date" />

	</label>
	<g:datePicker name="reminderDate" precision="day"  value="${todoInstance?.reminderDate}" default="none" noSelection="['': '']" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="todo.url.label" default="Url" />

	</label>
	<g:field type="url" name="url" value="${todoInstance?.url}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'done', 'error')} ">
	<label for="done">
		<g:message code="todo.done.label" default="Done" />

	</label>
	<g:checkBox name="done" value="${todoInstance?.done}" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'category', 'error')} ">
	<label for="category">
		<g:message code="todo.category.label" default="Category" />

	</label>
	<g:select id="category" name="category.id" from="${es.ua.expertojava.todo.Category.list()}" optionKey="id" value="${todoInstance?.category?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'tags', 'error')} ">
	<label for="tags">
		<g:message code="todo.tags.label" default="Tags" />
		<g:select multiple id="tags" name="todo.tags" from="${es.ua.expertojava.todo.Category.list()}" optionKey="id" value="${todoInstance?.tags?.id}" class="many-to-one" noSelection="['null': '']"/>
	</label>


</div>

grails/todo/grails-app/views/todo/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="report" action="report"><g:message code="default.report.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-todo" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${todoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${todoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:todoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/edit.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="report" action="report"><g:message code="default.report.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-todo" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${todoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${todoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:todoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${todoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/index.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="report" action="report"><g:message code="default.report.label" args="[entityName]" /></g:link></li>
				<!-- <li><g:link class="create" controller="searchableMod" action="index"><g:message code="default.buscador.label" default="Buscador"/></g:link></li> -->
				<li>
					<g:form url="[resource:todoInstance, action:'searchTodos']" >
						<fieldset class="form">
							<g:textField name="query" value="${params.query}"/>
							<g:submitButton name="submit" value="Search" />
						</fieldset>
					</g:form>
				</li>
			</ul>
		</div>
		<div id="list-todo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="edit" title="Edit" style="text-align:center"/>

						<g:sortableColumn property="delete" title="Delete" style="text-align:center"/>

						<g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />


						<g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}"style="text-align:center" />


						<g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />

						<g:sortableColumn property="done" title="${message(code: 'todo.done.label', default: 'Done')}" style="text-align:center"/>

					</tr>
				</thead>
				<tbody>
				<g:each in="${todoInstanceList}" status="i" var="todoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td style="text-align:center">
							<g:link class="edit" action="edit" resource="${todoInstance}"><button><i class="fa fa-pencil"></i></button></g:link>
						</td>
						<td style="text-align:center">
							<g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
							<!--
								<g:link class="delete" action="submit" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"><i class="fa fa-times"></i></g:link>
							-->
								<button type="submit" class="delete" value="Save" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"><i class="fa fa-times"></i></button>
							</g:form>
						</td>

						<td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>


						<td style="text-align:center"><g:formatDate format="dd-MM-yyyy" date="${todoInstance.date}"/></td>


						<td>${fieldValue(bean: todoInstance, field: "url")}</td>

						<td style="text-align:center"><todo:printIconFromBoolean value="${todoInstance.done}" /></td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${todoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails/todo/grails-app/views/todo/report.gsp
<%@ page import="es.ua.expertojava.todo.Category" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-category" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div id="list-category" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
						<g:sortableColumn property="name" title="${message(code: 'category.name.label', default: 'Name')}" />
					</tr>
				</thead>
				<tbody>
					<g:form url="[resource:todoInstance, action:'reportByCategory']" >
						<fieldset class="form">
							<g:each in="${categoryInstanceList}" status="i" var="categoryInstance">
								<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
									<td><g:checkBox name="selectedCategories" value="${fieldValue(bean: categoryInstance, field: "id")}" checked="true"/><label>${fieldValue(bean: categoryInstance, field: "name")}</label></td>
								</tr>
							</g:each>
						</fieldset>
						<fieldset class="buttons">
							<g:submitButton name="submit" value="Filtrar" />
						</fieldset>
					</g:form>
				</tbody>
			</table>
		</div>
	</body>
</html>